// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOUT.Models;

namespace SOUT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191215150226_OfferSeedData")]
    partial class OfferSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SOUT.Models.Offer", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AdditionalBaggage");

                    b.Property<string>("CityFrom");

                    b.Property<string>("CityTo");

                    b.Property<string>("Description");

                    b.Property<string>("MaxSize");

                    b.Property<string>("MaxWeight");

                    b.Property<string>("OfferType");

                    b.Property<int>("PassengerLimit");

                    b.Property<string>("UserID");

                    b.Property<string>("UserImage");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AdditionalBaggage = false,
                            CityFrom = "Brzeszcze",
                            CityTo = "Wałbrzych",
                            PassengerLimit = 0
                        });
                });

            modelBuilder.Entity("SOUT.Models.Request", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AdditionalBaggage");

                    b.Property<string>("CityFrom");

                    b.Property<string>("CityTo");

                    b.Property<string>("Description");

                    b.Property<bool>("IsFragile");

                    b.Property<int>("PassengerAmmount");

                    b.Property<string>("RequestType");

                    b.Property<string>("Size");

                    b.Property<string>("UserID");

                    b.Property<string>("UserImage");

                    b.Property<string>("UserName");

                    b.Property<string>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
